<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Opening View</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="/phpInitialDemo/web/stylesheets/style.css">
</head>




<body>
  
<?php echo $this->content(); ?>

</body>
</html>